baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
googleAnalytics = "UA-160603816-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
paginate = 5

custom_css = ["static/css/font-awesome.min.css"]
custom_js  = []

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false
  

[languages]
  [languages.en]
    title = "R programming"
    subtitle = "STA 326 2.0 Programming and Data Analysis with R"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Home: STA 326 2.0"
      logoHomeLink = "/home"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "schedule"
        name = "Schedule"
        url = "/schedule"

      [[languages.en.menu.main]]
        identifier = "archive"
        name = "Archive"
        url = "/archive"
        
      [[languages.en.menu.main]]
        identifier = "discussion"
        name = "Discussion Forum"
        url = "https://lms.fas.sjp.ac.lk/"
        
      [[languages.en.menu.main]]
        identifier = "swork"
        name = "Students' work"
        url = "https://hellor.netlify.app/coronareports/"