---
title: "MonteHall"
author: "Thiyanga Talagala"
date: "10/03/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, comment=NA}
reveal_host_choice <- function(door) {
door.allocation <- sample(c("goat","goat","car"))
notchosen <- c(1:3)[-door]
if (door.allocation[door] == "goat") {
if (door.allocation[notchosen[1]] =="goat")
host_choice = paste(door.allocation[notchosen[1]],
paste("door", notchosen[1], sep=" "), sep="-")
else
host_choice = paste(door.allocation[notchosen[2]],
paste("door", notchosen[2], sep=" "), sep="-")
}
else {
d <- sample(notchosen, 1)
host_choice = paste(door.allocation[d], paste("door", d, sep=" "), sep="-")
}
return(host_choice)
}

reveal_host_choice(1)
```


\newpage

```{r, comment=NA}
play_montehall <- function(door, strategy="switch") {
door.allocation <- sample(c("goat","goat","car"))
notchosen <- c(1:3)[-door]
host_choice <- sample(notchosen, 1) # player choice is car

if (door.allocation[door] == "goat") { # player chice is goat
host_choice <- ifelse (door.allocation[notchosen[1]] == "goat",
notchosen[1], notchosen[2])
}

# Now employ strategy
final_door <- door.allocation[door] # Strategy is to stay with original choice

if (strategy == "switch") {
d <- notchosen[which(notchosen != host_choice)]
final_door <- door.allocation[d]
}

final_door
}


play_montehall(1)
```

\newpage

```{r}
ncar.switch <- 0
for (i in 1:1000) {
if (play_montehall(door=1, strategy="switch") == "car")
ncar.switch <- ncar.switch+1
}
ncar.switch/1000

ncar.stay <- 0
for (i in 1:1000) {
if (play_montehall(door=1, strategy="stay") == "car")
ncar.stay <- ncar.stay+1
}
ncar.stay/1000

```

