---
title: "Pipe operator"
date: "12/05/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Necessary packages

```{r}
library(magrittr)
library(tidyverse)
library(stringr)
```

1. Explore the outputs of the following functions.

```{r,comment=NA}
x <- c(1,2)
sum(x, 3)
x %>% sum(3)
sum(x, 3) == x %>% sum(3)
```


```{r,comment=NA}
seq(3, 10, 2)
3 %>% seq(10, 2)
10 %>% seq(3, ., 2)
```

```{r,comment=NA}
# method 1
filter(iris, Sepal.Length >= 7.0)
# method 2 - using pipe
iris %>% filter(Sepal.Length >= 7.0)
```

```{r, comment=NA}
# method 1
ir <- as_tibble(iris)
select(ir, Species)
# method 2 - using pipe
iris %>% as_tibble() %>% select(Species)
```

2. Write the following code using the pipe operator.

```{r, comment=NA}
str_c("good", sample(c("health", "food", "work", "day"), 1))
```

What does the function `str_c` do?

Joins two or more vectors element-wise into a single character vector.

Answer:

```{r, comment=NA}
c("health", "food", "work", "day") %>%
    sample(1) %>% 
    str_c("good", .)
```

3. Write the following code using the pipe operator.


```{r, comment=NA}
summarize(filter(iris, Species=="setosa"), median(Sepal.Length))
```

Answer:

```{r, comment=NA}
iris %>%
  filter(Species=="setosa") %>%
  summarize(median(Sepal.Length))
```



